#!/bin/sh

# shellcheck source=/dev/null
. /etc/default/kpxc-ovpn.conf

printf "Type your KeePassXC vault password:\n"
CREDS=$(keepassxc-cli show "$VAULT" "$KEY" -a UserName -a Password -q)
printf "%s" "$CREDS" | sudo openvpn --config "$OVPNFILE" --auth-user-pass /dev/stdin
